language: java
jdk:
  - oraclejdk8

services:
  - docker

install:
  - ./gradlew build -x check --no-daemon

script: ./gradlew check javadoc --no-daemon && ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
