language: java
jdk:
  - openjdk8

services:
  - docker

install:
  - ./gradlew build -x check --no-daemon

script: ./gradlew check javadoc --no-daemon && ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - ./gradlew clean
  - ./gradlew jar
  - export RELEASEVERSION="v$(./gradlew version -q)"

deploy:
  - provider: releases
    api_key: "$GH_TOKEN"
    file_glob: true
    file: "build/libs/*"
    skip_cleanup: true
    name: $RELEASEVERSION
    on:
      branch: master
      jdk: openjdk8
